### PR TITLE
Updated index.html

### PR DESCRIPTION
**Pull request by blackNoir2**
Updated index.html: by adding images that will be used  for content placeholder image, including a banner that will contain one joke from API, and updated the CSS

### CODE REVIEW

**Comment by zz-hh-aa** [comment]
Thanks Egbie! I `git fetch`'d and ran the project locally and now `index.html` is rendering like this (including whitespace at bottom): 
image
I'm guessing this isn't what you intended? 

Also, I see you're including a message in the commit body, which is useful--I'd find it helpful for reviewing if they (and the commit subject / header) had a little more detail. For reference, I found the examples [here](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/) under "Commit Message Comparisons" helpful.

**Comment by zz-hh-aa** [comment]
Thanks! 

When I moved `index.html` into `static` before, I was confused--so I asked ChatGPT about it, and it seems that ultimately it should remain there because the file _itself_ is static. Google Bard also recommended structuring via `routes` and `views` directories:
> Inside your project folder, create a folder named routes. This folder will store JavaScript files containing code for handling different routes (URLs) in your application.
> Create another folder named views. Here you'll store your HTML template files that define the structure and content of your web pages.
which could be an alternative option. Maybe we can discuss what makes more sense later!
 
Here's ChatGPT's full response about `index.html` living in the `static` folder if useful:
> Even though index.html includes dynamic content that's updated through JavaScript and API calls, it's still considered a static file from the perspective of the web server. Here's why it makes sense for index.html to reside in the static folder:
> 
> 1. Definition of Static Files: Static files are those that don't change from one request to another or don't need to be compiled at runtime. They are sent to the client's browser as they are stored on the server. This includes HTML, CSS, JavaScript, images, and other multimedia content. Even if a JavaScript file included in your HTML dynamically updates part of the page's content, the HTML and JavaScript files themselves do not change on the server—they are served "as-is".
> 
> 2. Server Configuration: Web servers, including those created with Express, are often configured to serve all the files in a designated directory (like static or public) as static assets. This simplifies the setup, as the server doesn't need to have separate logic to determine how to handle requests for common file types like HTML, CSS, and client-side JavaScript.
> 
> 3. Client-Side Rendering: Your setup seems to rely on client-side JavaScript to dynamically update the page's content. This is a common pattern where the initial HTML page is static, but JavaScript running in the browser makes API calls (to your own server or external services) and updates the DOM based on the responses. This approach allows for dynamic interaction without the need for the HTML file itself to be generated dynamically on the server.
> 
> 4. Separation of Concerns: Keeping index.html in the static directory helps maintain a clear separation between the server-side application logic (e.g., handling API requests, interfacing with databases) and the client-side presentation layer (HTML, CSS, JavaScript). This separation of concerns makes the application easier to manage and scale.
> 
> 5. Caching and Performance: Static files can be efficiently cached by browsers and CDNs (Content Delivery Networks), reducing server load and improving load times for end users. Since index.html and other assets in the static folder don't change often, they are good candidates for caching.
> 
> In summary, index.html is kept in the static directory because it is, from the server's perspective, a static asset that is served directly to clients without modification. The dynamic behavior you see on the client side is achieved through JavaScript that runs in the browser, which can make your site appear very dynamic without the server having to generate unique HTML for each request.

**Comment by blackNoir2** [comment]
> Thanks!
> 
> When I moved `index.html` into `static` before, I was confused--so I asked ChatGPT about it, and it seems that ultimately it should remain there because the file _itself_ is static. Google Bard also recommended structuring via `routes` and `views` directories:
> 
> > Inside your project folder, create a folder named routes. This folder will store JavaScript files containing code for handling different routes (URLs) in your application.
> > Create another folder named views. Here you'll store your HTML template files that define the structure and content of your web pages.
> > which could be an alternative option. Maybe we can discuss what makes more sense later!
> 
> Here's ChatGPT's full response about `index.html` living in the `static` folder if useful:
> 
> > Even though index.html includes dynamic content that's updated through JavaScript and API calls, it's still considered a static file from the perspective of the web server. Here's why it makes sense for index.html to reside in the static folder:
> > 
> > 1. Definition of Static Files: Static files are those that don't change from one request to another or don't need to be compiled at runtime. They are sent to the client's browser as they are stored on the server. This includes HTML, CSS, JavaScript, images, and other multimedia content. Even if a JavaScript file included in your HTML dynamically updates part of the page's content, the HTML and JavaScript files themselves do not change on the server—they are served "as-is".
> > 2. Server Configuration: Web servers, including those created with Express, are often configured to serve all the files in a designated directory (like static or public) as static assets. This simplifies the setup, as the server doesn't need to have separate logic to determine how to handle requests for common file types like HTML, CSS, and client-side JavaScript.
> > 3. Client-Side Rendering: Your setup seems to rely on client-side JavaScript to dynamically update the page's content. This is a common pattern where the initial HTML page is static, but JavaScript running in the browser makes API calls (to your own server or external services) and updates the DOM based on the responses. This approach allows for dynamic interaction without the need for the HTML file itself to be generated dynamically on the server.
> > 4. Separation of Concerns: Keeping index.html in the static directory helps maintain a clear separation between the server-side application logic (e.g., handling API requests, interfacing with databases) and the client-side presentation layer (HTML, CSS, JavaScript). This separation of concerns makes the application easier to manage and scale.
> > 5. Caching and Performance: Static files can be efficiently cached by browsers and CDNs (Content Delivery Networks), reducing server load and improving load times for end users. Since index.html and other assets in the static folder don't change often, they are good candidates for caching.
> > 
> > In summary, index.html is kept in the static directory because it is, from the server's perspective, a static asset that is served directly to clients without modification. The dynamic behavior you see on the client side is achieved through JavaScript that runs in the browser, which can make your site appear very dynamic without the server having to generate unique HTML for each request.

Yes that is true if the page was static but the page itself is going to be dynamic. I took this from "If you're using Express.js, the express.static middleware is typically used to serve static files, such as HTML, CSS, images, and client-side JavaScript files. These files are served directly to the client without any processing from the server.

When you have dynamic content generated by Express.js routes, such as rendering HTML templates using a templating engine like EJS or handling API requests, it's generally separate from static files. The dynamic content is generated by server-side logic and then sent to the client.

**Comment by blackNoir2** [comment]
I am closing this pull request because I need to alter several things

**Pull request closed without merging**
